### ISSUE TITLE
Failed to make it work with Koa2

### ISSUE THREAD

**Issue by rankun203** [koa-modules/i18n#13]
With the code same to the example, I still got this error:

```
TypeError: this.request[(GET_PREFIX + m)] is not a function
```

<img width="737" alt="koa-i18n" src="https://cloud.githubusercontent.com/assets/2988555/24895091/29c0eb8e-1ec1-11e7-8682-8a544359add4.png">

Koa version: v2
koa-i18n version: 2.0.1
Node version: 7.7.4

**Comment by desaroger** [comment]
I wanted to use this library, but last commit is more than 1 year old and after knowing about this issue I will find some alternative. Please make it work with Koa 2! Thanks :D

**Comment by fundon** [comment]
Try https://github.com/koa-modules/i18n/releases/tag/v2.1.0.

**Comment by rankun203** [comment]
@fundon Still having this issue:

```
this.request[(GET_PREFIX + m)] is not a function
```

[index.js#52](https://github.com/koa-modules/i18n/blob/master/index.js#L52)

![image](https://cloud.githubusercontent.com/assets/2988555/24940096/a68ef37e-1f73-11e7-9fd5-af229a6b6071.png)

**Comment by rankun203** [comment]
I'll do further investigation on this later. Seems a function named `getLocaleFromQuery` is not attached on the request, should be a middleware problem.

**Comment by rankun203** [comment]
@desaroger It is working with Koa 2.

Just follow the README. I didn't read it carefully when I first started using this module, I just picked up some lines I thought would be enough to go. Anyway, now it's working like a charm, the performance is good.

**Comment by qishuo** [comment]
> @desaroger It is working with Koa 2.
> 
> Just follow the README. I didn't read it carefully when I first started using this module, I just picked up some lines I thought would be enough to go. Anyway, now it's working like a charm, the performance is good.

How to solve it?
