### ISSUE TITLE
Suggestion: hreflang headers

### ISSUE THREAD

**Issue by rbaprado** [koa-modules/i18n#7]
Hello,

I was reading https://support.google.com/webmasters/answer/189077?hl=en and thought it would be pretty nice if i18n had an option to automatically generate alternate language headers, it would definitely help with SEO. Would such thing be a possibility?

Great library, by the way.

**Comment by fundon** [comment]
@rbaprado Maybe you need to add `<link rel="alternate" hreflang="es" href="http://es.example.com/" />` into your layout template.
